admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Home:index }

admin_category_list:
    path: /categories
    defaults: { _controller: AdminBundle:Category:list }

admin_category_new:
    path: /newcategory
    defaults: { _controller: AdminBundle:Category:new }

admin_category_edit:
    path: /category/{id}
    defaults: { _controller: AdminBundle:Category:edit}

admin_category_delete:
    path: /category/delete/{id}
    defaults: { _controller: AdminBundle:Category:delete }
    
admin_job_list:
    path: /jobs
    defaults: { _controller: AdminBundle:Job:list }

admin_job_new:
    path: /newjob
    defaults: { _controller: AdminBundle:Job:new }

admin_job_edit:
    path: /job/{id}
    defaults: { _controller: AdminBundle:Job:edit}

admin_job_delete:
    path: /job/delete/{id}
    defaults: { _controller: AdminBundle:Job:delete }
