admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

jobz:
    resource: "@JobzBundle/Resources/config/routing.yml"
    prefix:   /