<?php

namespace JobzBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use JobzBundle\Entity\Category;
use JobzBundle\Entity\Job;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    /**
     * @param int $limit
     * @return Job[]
     */
    public function findLatest($limit = 10)
    {
        return $this->_em->getRepository("JobzBundle:Job")
            ->createQueryBuilder("j")
            ->orderBy("j.created", "DESC")
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Category $category
     * @return array
     */
    public function findByCategory(Category $category)
    {
        return $this->_em->getRepository("JobzBundle:Job")
            ->createQueryBuilder("j")
            ->orderBy("j.created", "DESC")
            ->where("j.category = :category")
            ->setParameter("category", $category)
            ->getQuery()
            ->getResult();
    }

    public function searchByKeywords($keyword)
    {
        return $this->createQueryBuilder("j")
            ->where("j.location LIKE :string")
            ->orWhere("j.position LIKE :string")
            ->orWhere("j.company LIKE :string")
            ->setParameter(":string", "%$keyword%")
            ->getQuery()
            ->getResult();
    }
}
